### ISSUE TITLE
FormattedPrint doesn't compile with Arduino SAMD core 1.8.x

### ISSUE THREAD

**Issue by JAndrassy** [jandrassy/StreamLib#1]
```
/home/duro/eclipse/arduinoPlugin/libraries/StreamLib/1.0.2/src/FormattedPrint.cpp:56:3: error: 'cookie_io_functions_t' was not declared in this scope
   cookie_io_functions_t fncs;
   ^~~~~~~~~~~~~~~~~~~~~
/home/duro/eclipse/arduinoPlugin/libraries/StreamLib/1.0.2/src/FormattedPrint.cpp:57:3: error: 'fncs' was not declared in this scope
   fncs.write = adapterWrite;
   ^~~~
/home/duro/eclipse/arduinoPlugin/libraries/StreamLib/1.0.2/src/FormattedPrint.cpp:57:3: note: suggested alternative: 'fls'
   fncs.write = adapterWrite;
   ^~~~
   fls
/home/duro/eclipse/arduinoPlugin/libraries/StreamLib/1.0.2/src/FormattedPrint.cpp:59:10: error: 'fopencookie' was not declared in this scope
   return fopencookie(p, "w", fncs);
```
in stdio.h are added ifdefs which exclude 'cookie' section
